### ISSUE TITLE
缺少一些文件

### ISSUE THREAD

**Issue by aDecisionTree** [weiyinwei/MMGCN#1]
visual_feat.pt
audio_feat.pt
textual_feat.pt
作者你好！最近在看你们MMGCN的文章，想运行一下代码，请问这些文件能给一下吗？ 如果你能说明一下是怎么得到这些文件的，那就最好了，谢谢！

**Comment by weiyinwei** [comment]
您好，感谢关注，之前的分享链接失效了，我正在重新上传数据中，预计下周可以进行下载。具体如何获得请参考论文相关章节。

**Comment by aDecisionTree** [comment]
嗯嗯，非常感谢你的回复 :-)
