### ISSUE TITLE
about the  multi-modal feature NGCF

### ISSUE THREAD

**Issue by yuanyuansiyuan** [weiyinwei/MMGCN#10]
In your paper, "For a fair comparison,
we regard the multi-modal features of micro-video as side
information and feed them into the framework to predict the
interactions between the users and items". I am curious about that how to feed the multi-modal features into the standard NGCF model, by taking the multi-modal features as the initial embeddings of users and items, or other ways?

**Comment by weiyinwei** [comment]
Thanks for your attention. 
As you mentioned above, we feed the items' concatenated multimodal features as their representations of nodes, but randomly initialize the representations of user nodes. By performing the proposed model, user representations are learned.
