### ISSUE TITLE
About movielens description data

### ISSUE THREAD

**Issue by srtianxia** [weiyinwei/MMGCN#11]
Where did the movie descriptions come from, and which toolkit did you use? Thanks!

**Comment by weiyinwei** [comment]
Thanks for your attention.
The descriptions or the extracted features are released by their owners. 
You may collect them from the website of Movielens. 
Unfortunately, there is no raw data in Tiktok and Kwai.

**Comment by srtianxia** [comment]
> The descriptions or the extracted features are released by their owners.

Can you provide me with a link to the description data for movielens? thanks!

**Comment by srtianxia** [comment]
@weiyinwei
