### ISSUE TITLE
current state of the codebase

### ISSUE THREAD

**Issue by WANG-KX** [weiyinwei/MMGCN#14]
I notice that you have removed many files from the database and the folders are empty now. There is even no train.py. May I ask why?

Also the BaiduPan requires a password for downloading. What's the password to download it?

**Comment by weiyinwei** [comment]
I do have Train.py. Please check it again. For the dataset, we are asked by the owners of them that we cannot release the datasets directly.
The password is zsye.

**Comment by WANG-KX** [comment]
Hi, thanks for you reply.

I'm more confused. You mean, for example, `python **train.py** --model_name='MMGCN' --l_r=0.0005 --weight_decay=0.1 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False
` actually means `python **Train.py** --model_name='MMGCN' --l_r=0.0005 --weight_decay=0.1 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False
`?

**Comment by weiyinwei** [comment]
I am sorry for that. I forgot about this statement. It should be 'main.py'. Since I updated my source code. Thanks a lot. I will update it as soon as possible.

**Comment by weiyinwei** [comment]
Hi,

I am sorry for your confusion. Please use ‘main.py’ directly, for example, python main.py --model_name='MMGCN' --l_r=0.0005 --weight_decay=0.1 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False.

Best,
Yinwei
发件人: WANG KAIXUAN<mailto:notifications@github.com>
发送时间: 2020年9月14日 10:03
收件人: weiyinwei/MMGCN<mailto:MMGCN@noreply.github.com>
抄送: weiyinwei<mailto:weiyinwei@hotmail.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [weiyinwei/MMGCN] current state of the codebase (#14)


Hi, thanks for you reply.

I'm more confused. You mean, for example, python **train.py** --model_name='MMGCN' --l_r=0.0005 --weight_decay=0.1 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False actually means python **Train.py** --model_name='MMGCN' --l_r=0.0005 --weight_decay=0.1 --batch_size=1024 --dim_latent=64 --num_workers=30 --aggr_mode='mean' --num_layer=2 --concat=False ?

―
