### ISSUE TITLE
论文中使用的处理过的数据集可以提供一下吗

### ISSUE THREAD

**Issue by yaoodng7** [weiyinwei/MMGCN#18]
您好，我对MMGCN的工作很感兴趣，请问论文中使用的处理过的数据方便提供一下吗，希望可以复现论文中的结果

**Comment by weiyinwei** [comment]
I have replied to your email. Please check it.

**Comment by LinJayan** [comment]
您好！对MMGCN的研究很感兴趣，可以提供下使用的数据集吗，或者处理数据的代码程序，非常感谢！希望复现下论文。

**Comment by weichentangming** [comment]
> 您好，我对MMGCN的工作很感兴趣，请问论文中使用的处理过的数据方便提供一下吗，希望可以复现论文中的结果

你好，请问你现在复现了吗，这边数据集能提供下吗

**Comment by yaoyuanyuanyyy** [comment]
> 

您好 请问可以分享一下数据集吗？
