### ISSUE TITLE
Some dataset problems

### ISSUE THREAD

**Issue by Arieslady** [weiyinwei/MMGCN#2]
Dear authors, your mmgcn paper is very interesting and inspiring! However, the hyperlinks that point to the Kwai and Tiktoc datasets have removed or invalidate the urls to the original datasets. So im wondering if you are planning to release your extracted features or a copy of the original datasets? Thank you very much.

**Comment by weiyinwei** [comment]
Thanks for your attention! But, I am afraid that I have no right to release the datasets directly. According to Tiktok’s requirements, we have to download from their URLs. You can email them (https://drive.google.com/drive/folders/142VG4_VieVvG-C6mizRtmQeVzCl2Af0-?usp=sharing). For the Kwai dataset, I am trying my best to apply for authorization. Please wait a couple of days.

**Comment by Arieslady** [comment]
Thank you for your reply and your efforts! Actually, the e-mail provided Tiktok dataset is full and can no longer receive any emails... But I happen to notice that in another closed issue you mentioned that you were intended to release the .pt feature file? If its true, that'll be really nice! Thank you again!
