### ISSUE TITLE
MovieLens 数据集

### ISSUE THREAD

**Issue by libeibei95** [weiyinwei/MMGCN#20]
MovieLens 的数据集作者公开了吗？可以分享下吗？最近在做短视频推荐相关研究。

谢谢

email libeibei16@otcaix.iscas.ac.cn

**Comment by weiyinwei** [comment]
movielens作者已经公开了全部数据，您可以通过官方地址很容易的获取到movielens的全部数据。

**Comment by libeibei95** [comment]
MMGCN 中 movielens 的多模态数据集有公开吗？我好像没有找到

快手数据集可以分享吗？仅用于科研。

麻烦作者了，谢谢回复

**Comment by weiyinwei** [comment]
movielens给出了每个video的id，可以很容易从YouTube上爬取到对应的视频，按照论文中所描述预处理方法进行处理即可。
由于版权问题，快手的数据我没有办法直接公开，建议您与数据所有者直接进行联系，下载地址我论文中已经给出。

**Comment by libeibei95** [comment]
好的，谢谢回复
