### ISSUE TITLE
graph的构建

### ISSUE THREAD

**Issue by weichentangming** [weiyinwei/MMGCN#22]
你好，想问下，graph是怎么构建的，是所有的users,和 items,根据交互参与构建一张图嘛？ 那这样会不会需要很大显存？

**Comment by weiyinwei** [comment]
是的，一般服务器显存是没有问题的。

**Comment by weichentangming** [comment]
> 是的，一般服务器显存是没有问题的。
ok, 谢谢

**Comment by weichentangming** [comment]
> > 是的，一般服务器显存是没有问题的。
> > ok, 谢谢
