### ISSUE TITLE
使用toy dataset中的数据代码无法运行

### ISSUE THREAD

**Issue by feiyuchen7** [weiyinwei/MMGCN#23]
你好，
感谢你的工作和开源代码！我尝试toy dataset运行MMGCN和GRCN的时候都出现类似的问题。模态数据在一些隐含层的长度不一致使得代码无法运行。比如，在使用movielens运行MMGCN时报错：

> Data loading ...
Data has been loaded.
Now, training start ...
  0%|                                                                                                                                                                           | 0/2071 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 94, in <module>
    loss = train(epoch, len(train_dataset), train_dataloader, model, optimizer, batch_size, writer)
  File "/home/xxx/MMGCN/Train.py", line 19, in train
    loss, model_loss, reg_loss, weight_loss, entropy_loss = model.loss(user_tensor, item_tensor)
  File "/home/xxx/MMGCN/Model_MMGCN.py", line 126, in loss
    out = self.forward()
  File "/home/xxx/MMGCN/Model_MMGCN.py", line 112, in forward
    v_rep = self.v_gcn(self.v_feat, self.id_embedding)
  File "/home/xxx/projects/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/MMGCN/Model_MMGCN.py", line 63, in forward
    x_hat = F.leaky_relu(self.linear_layer1(x)) + id_embedding if self.has_id else F.leaky_relu(self.linear_layer1(x))#equation 5
RuntimeError: The size of tensor a (56626) must match the size of tensor b (61471) at non-singleton dimension 

我输出数据维度之后得到以下维度，因为0维不同所以无法相加：

> self.linear_layer1(x).shape: torch.Size([56626, 64])
id_embedding.shape: torch.Size([61471, 64])

同样的问题甚至数字在我运行GRCN时也出现：

> Traceback (most recent call last):
  File "main.py", line 118, in <module>
    loss = train(epoch, len(train_dataset), train_dataloader, model, optimizer, batch_size, writer)
  File "/home/xxx/GRCN/Train.py", line 19, in train
    loss, model_loss, reg_loss, weight_loss, entropy_loss = model.loss(user_tensor, item_tensor)
  File "/home/xxx/GRCN/Model_routing.py", line 219, in loss
    out = self.forward()
  File "/home/xxx/GRCN/Model_routing.py", line 207, in forward
    representation = torch.cat((id_rep, content_rep), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 56626 and 61471 (The offending index is 0)

在我尝试使用tiktok数据集时在同样的位置报错，只是数据大小不一样。看起来像是toy dataset 处理之后数据维度有一些不一致。
请问是我在代码哪里处理得不对吗？有什么建议可以更正的吗？
十分感谢你的帮助

**Comment by weiyinwei** [comment]
行数代表item和user个数，但是toy dataset的user和item个数与完整版有区别，您需要手动改动一下。

**Comment by feiyuchen7** [comment]
感谢您的回复！
我看了数据文件之后把item个数改为了1141，item个数依然是55485，之前提到的地方不再报错，但在validation的时候报错：

> Val start...
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    val_precision, val_recall, val_ndcg = full_vt(epoch, model, val_data, 'Val', writer)
  File "/home/xxx/MMGCN/Full_vt.py", line 12, in full_vt
    precision, recall, ndcg_score = model.full_accuracy(data)
  File "/home/xxx/MMGCN/Model_MMGCN.py", line 206, in full_accuracy
    score_matrix[row][col] = 1e-5
RuntimeError: CUDA error: device-side assert triggered


似乎还是数据/标签 维度的问题，请问是我改的数字不对或者是其他问题吗？

**Comment by weiyinwei** [comment]
应该还是类似的问题

**Comment by feiyuchen7** [comment]
请问toy dataset的item和user的具体个数可以告知一下吗？

**Comment by feiyuchen7** [comment]
十分感谢，我将数据改为num_user = 100  num_item = 1141之后 代码已经可以正常运行

另外还有两个问题想请问一下：

1.tiktok数据集，我看官方网站上有两个track，不知道您使用的是哪个track的数据？track2依然是千万级别的数据，在您的paper中有36656个user，不知道是否有选取user ID/item ID相关的文件，还是使用的整个完整的track？

2.是否有可能release数据特征生成的代码文件呢？就是从raw data到类似于toy dataset中的feature的过程的文件，即提取处理数据，生成.npy/.pt特征过程的代码文件

再次感谢您的耐心~

**Comment by weiyinwei** [comment]
您好，您可以按照时间周期选择interactions，然后获得相应的user和item。item模态不全的需要进行删除。特征是数据所有者release的，并没有提供raw data。

**Comment by ldk-coder** [comment]
> 回溯（最近调用最后一次）：文件 “main.py”，第 107 行，以 val_precision 为单位，val_recall，val_ndcg = full_vt（纪元，模型，val_data，'Val'，写入器） 文件 “/data/wenzh/yaoyuanyuan/MMGCN-master-1028/Full_vt.py”，第 12 行，精确full_vt，召回，ndcg_score = model.full_accuracy（data） 文件 “/data/wenzh/yaoyuanyuan/MMGCN-master-1028/Model_MMGCN.py”，第 230 行，以 full_accuracy items_list = all_index_of_rank_list[user].tolist（） IndexError：索引 0 超出大小为 0 的维度 0 的边界
> 
> 请问您在复现过程中是否遇到以上问题？是如何解决的呢？

您好我也遇到了这个问题，请问您是怎么解决的

**Comment by ldk-coder** [comment]
@yaoyuanyuanyyy 请问你这个问题解决了吗，具体是怎么做的呢
