### ISSUE TITLE
Tiktok 数据集 

### ISSUE THREAD

**Issue by weichentangming** [weiyinwei/MMGCN#24]
你好：
      tiktok数据集中，track2中的title文件中，里面的特征是字典的形式，比如{'24':1, '25':2}, 请问这个字典的含义是什么啊，以及你是怎么处理为128维特征的啊？
      万分感谢

**Comment by weiyinwei** [comment]
您好，该数据为脱敏数据，您可以理解为‘24’对应的单词在句子中出现1次，‘25’对应单词出现1次。句子的feature是由所有单词的word embedding平均得到的。

**Comment by weichentangming** [comment]
> 您好，该数据为脱敏数据，您可以理解为‘24’对应的单词在句子中出现1次，‘25’对应单词出现1次。句子的feature是由所有单词的word embedding平均得到的。
感谢回答。 那每个单词 embedding 你是怎么做的啊？

**Comment by weiyinwei** [comment]
没有什么特殊的操作，每个单词随机初始化为一个向量进行学习就好。

**Comment by struggle123456789** [comment]
> 你好： tiktok数据集中，track2中的title文件中，里面的特征是字典的形式，比如{'24':1, '25':2}, 请问这个字典的含义是什么啊，以及你是怎么处理为128维特征的啊？ 万分感谢
你好，请问tiktok数据集是完整数据集吗，在哪下载的，可以说一下吗

**Comment by struggle123456789** [comment]
> > 您好，该数据为脱敏数据，您可以理解为‘24’对应的单词在句子中出现1次，‘25’对应单词出现1次。句子的feature是由所有单词的word embedding平均得到的。
> > 感谢回答。 那每个单词 embedding 你是怎么做的啊？

你好，想问一下你的tiktok数据集是完整数据集吗，在哪下载的可以提供一下下载地址吗，万分感谢

**Comment by struggle123456789** [comment]
> 你好： tiktok数据集中，track2中的title文件中，里面的特征是字典的形式，比如{'24':1, '25':2}, 请问这个字典的含义是什么啊，以及你是怎么处理为128维特征的啊？ 万分感谢

您好，您的tiktok数据集是完整数据集吗，在哪下载的可以提供一下下载地址吗，万分感谢

**Comment by weiyinwei** [comment]
您好，我已经在论文中给出了下载链接。

**Comment by Song-xx** [comment]
> 

你哪里下到的数据集啊，现在还能下到吗

**Comment by hdu-yzl** [comment]
> > 你好： tiktok数据集中，track2中的title文件中，里面的特征是字典的形式，比如{'24':1, '25':2}, 请问这个字典的含义是什么啊，以及你是怎么处理为128维特征的啊？ 万分感谢
> 
> 您好，您的tiktok数据集是完整数据集吗，在哪下载的可以提供一下下载地址吗，万分感谢

您好，请问你当时拿到完整的数据集了吗

**Comment by xjn1207** [comment]
您好，进入数据集下载地址已经无法下载了，请问能分享网盘吗？万分感谢
