### ISSUE TITLE
多模态

### ISSUE THREAD

**Issue by xiaole-wang** [weiyinwei/MMGCN#27]
你好：
能否麻烦共享一下爬取movielens数据集多模态数据的方法和代码，不胜感激！

**Comment by weiyinwei** [comment]
您可以参考我CLCRec这个项目，里面有数据。

**Comment by xiaole-wang** [comment]
非常感谢您的回复。我今天阅读了一下您的CLCRec这个项目的Github代码。由于我是今年刚接触推荐，也是刚开始学习python这门语言，所以看的不是太懂。还是不太懂怎么构建数据集，能不能麻烦您稍微解释一下您的这个代码具体是怎么运行的。这可能会浪费您非常宝贵的时间，万分感谢您！
如您的时间确实比较紧张，还是非常感谢您回复邮件并给我指导。祝您工作顺利，身体健康！

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月8日(周日) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [weiyinwei/MMGCN] 多模态 (#27)




 
您可以参考我CLCRec这个项目，里面有数据。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaole-wang** [comment]
非常感谢您的回复。我今天阅读了一下您的CLCRec这个项目的Github代码。由于我是今年刚接触推荐，也是刚开始学习python这门语言，所以看的不是太懂。还是不太懂怎么构建数据集，能不能麻烦您稍微解释一下您的这个代码具体是怎么运行的。这可能会浪费您非常宝贵的时间，万分感谢您！如您的时间确实比较紧张，还是非常感谢您回复邮件并给我指导。祝您工作顺利，身体健康！---原始邮件---发件人: ***@***.***>发送时间: 2021年8月8日(周日) 下午4:07收件人: ***@***.***>;抄送: ***@***.******@***.***>;主题: Re: [weiyinwei/MMGCN] 多模态 (#27)
您可以参考我CLCRec这个项目，里面有数据。
