### ISSUE TITLE
论文使用的参数配置，epoch数目

### ISSUE THREAD

**Issue by chuanfaTian** [weiyinwei/MMGCN#28]
您好：
请问论文里面使用的参数配置，以及epoch数目。我跑这个代码在MovieLens数据集上的实验结果（如图1，取收敛前最佳结果）与您论文中的各项指标（图二）都差距挺大，几乎缩水了一半。请问这是什么原因呢？万分感激
![image](https://user-images.githubusercontent.com/86607516/128704315-e861c4a3-8b22-4c3d-8978-fcbd0e483c47.png)
![image](https://user-images.githubusercontent.com/86607516/128704514-e5fb2acd-378f-4718-8d30-20e3ccab1fad.png)
@weiyinwei

**Comment by weiyinwei** [comment]
您好，我论文中report的结果是1000个负例的测试，代码是我更新过的，现在是full ranking。

**Comment by chuanfaTian** [comment]
> 您好，我论文中report的结果是1000个负例的测试，代码是我更新过的，现在是full ranking。
老师您好，感谢您的回复，由于我刚接触推荐工作，不是很熟悉，麻烦您请教您一个问题提：现在这份代码如何修改能得到论文结果.这将对我后续的工作有很大的帮助,感谢您！

**Comment by chuanfaTian** [comment]
老师您好，感谢您的回复，由于我刚接触推荐工作，不是很熟悉，麻烦您请教您一个问题提：现在这份代码如何修改能得到论文结果.这将对我后续的工作有很大的帮助,感谢您！
@weiyinwei

**Comment by weiyinwei** [comment]
您可以在evaluation时候进行1000负采样，可以得到接近的结果。但是原负采样数据我已经找不到了，所以没有办法再提供了。
