### ISSUE TITLE
Question about movielens datasets

### ISSUE THREAD

**Issue by auhjin** [weiyinwei/MMGCN#3]
I'm interesting in multi-modal recommendation recently，but movielens datasets lack of text information，I just got the image information. so I want you can share and upload datasets firstly，thank you！！

**Comment by weiyinwei** [comment]
Thanks for your interesting. Actually, I am reorganizing the dataset because of some copyright problems. I will release them in a couple of weeks.

**Comment by srtianxia** [comment]
@weiyinwei  Where did the movie descriptions come from, and which toolkit did you use? Thanks!
