### ISSUE TITLE
关于论文实验的baseline的代码文件

### ISSUE THREAD

**Issue by chuanfaTian** [weiyinwei/MMGCN#30]
老师您好，由于GitHub上的代码您提到过是用的full ranking，现在我想把论文中的baseline的方法直接用full ranking 来评估NDCG，Precision，Recall等实验指标，老师麻烦您可不可以提供下相关的py文件，叨扰您了

**Comment by weiyinwei** [comment]
我提供的代码就是full ranking的，您可以直接使用。
