### ISSUE TITLE
关于实验论文中的baseline文件

### ISSUE THREAD

**Issue by chuanfaTian** [weiyinwei/MMGCN#31]
老师您好，由于GitHub上的代码您提到过是用的full ranking，现在我想把论文中的baseline的方法直接用full ranking 来评估NDCG，Precision，Recall等实验指标，老师麻烦您可不可以提供下相关的py文件，叨扰您了 @weiyinwei

**Comment by weiyinwei** [comment]
我提供的代码就是full ranking的，您可以直接使用。

**Comment by chuanfaTian** [comment]
老师我的意思是您能不能提供一下实验的基线VBPR,GraphSAGE,ACF,NGCF的代码 @weiyinwei

**Comment by weiyinwei** [comment]
不好意思，baseline代码我没有保存。建议直接联系论文作者或自己进行复现。

**Comment by chuanfaTian** [comment]
好的老师，谢谢您的回复
