### ISSUE TITLE
关于1000负样本ranking的一点明确

### ISSUE THREAD

**Issue by chuanfaTian** [weiyinwei/MMGCN#33]
老师您好，论文中是用到1000负样本ranking，请问：test过程中是正样本1个，负样本1000个，即ranking样本为1001个；还是正负采样比为1：1000，即如果正样本有n个，ranking总样本数1000n+n；
![812effd3d691da63444657252fa3d75](https://user-images.githubusercontent.com/86607516/133193984-a029128c-d4fd-432d-be0b-61bafbfece29.png)

图片是论文中提到的部分，就是向您确认一下，负样本一共1000个，正样本1个；还是怎么样？

**Comment by weiyinwei** [comment]
是1000个负例，不是比例。

**Comment by chuanfaTian** [comment]
> 是1000个负例，不是比例。

那test过程中每个user节点的正样本的数量呢

**Comment by chuanfaTian** [comment]
感谢您的回复，那test过程中每个user节点的正样本的数量呢；是正样本1个，负样本1000个，即ranking样本为1001个么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiyinwei/MMGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiyinwei/MMGCN] 关于1000负样本ranking的一点明确 (#33)





 
是1000个负例，不是比例。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
