### ISSUE TITLE
老师您好，接上一个刚关闭的issue，还有一点没有明确

### ISSUE THREAD

**Issue by chuanfaTian** [weiyinwei/MMGCN#34]
感谢您的回复，每个user负样本是1000来ranking，那test过程中每个user节点的正样本的数量呢；是正样本1个，负样本1000个，即ranking样本为1001个么？

**Comment by weiyinwei** [comment]
您好，抱歉回复晚了，你理解是正确的。正样本数量根据划分结果，不同的user可能在testing中有不同数量的pos items。
