### ISSUE TITLE
关于每个模态的graph

### ISSUE THREAD

**Issue by Betternw** [weiyinwei/MMGCN#36]
您好，请问提取了视觉听觉等信息后，是如何为每个模态建立graph的呢？可以告知用了什么模型或者方法吗？看前面说工作中未包含构建graph不太理解，那么数据的graph是如何获得的呢。
感谢回复。

**Comment by weiyinwei** [comment]
您好，graph是建立在user-item interactions的关系上的，没有什么模型或方法，单纯考虑historical records。
