### ISSUE TITLE
数据处理问题

### ISSUE THREAD

**Issue by Cleanspeech317** [weiyinwei/MMGCN#38]
请问您在筛选tiktok训练集的时候有用到‘finish’和‘like’两个字段么，还有我看您提供的样例数据里用户id和项目id可以是重复一样的（都是从0开始），这样是可以的吗？在最后提取图节点嵌入表示结果result_embedding的时候不会分不清项目表示和用户表示么？感谢您的回答！

**Comment by weiyinwei** [comment]
我只考虑了interaction，无论是否finish或like，都被认为是interacted。 可以分别创建embedding matrix，也可以统一编码，例如读入item id后，给他加上user的个数。

**Comment by Cleanspeech317** [comment]
只是单纯的按照时间戳进行筛选吗？这样不会造成在测试集负采样的过程中该用户在时间戳外交互了的项目在测试集中被采样成负样本么造成误差么？

**Comment by Cleanspeech317** [comment]
还有我看论文里提到了视频长度3-15秒，对视频的长度也进行了筛选么？
