### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by PingjieTang** [weiyinwei/MMGCN#4]
I am trying to reach the tiktok and kwai datasets by using the links provided in the repository. However, it appears those two datasets are not publicly available anymore after challenges closed. Are there any alternative ways to get the data? Thanks.

**Comment by weiyinwei** [comment]
I am sorry for the delayed reply. Thanks for your attention. 
Indeed, I have noticed that. 
But, I have no right to release these datasets.
