### ISSUE TITLE
数据集选择交互

### ISSUE THREAD

**Issue by 1xiaoyuanS** [weiyinwei/MMGCN#40]
作者您好，我看到您在别的问题解答中提到，您使用时间周期去选择交互，请问你选择的时候用的是track2中的time字段吗？能否详细告知一下是如选择的，比如您在这篇文章中所设置的time字段的范围？非常感谢！

**Comment by weiyinwei** [comment]
您好，非常感谢对于我们工作的关注。具体的时间我已经忘记了，您可以根据interaction的数量选择合适的时间，并没有过多的技巧，但是需要注意要过滤掉信息不完整的item，以及对应的interaction。

**Comment by 1xiaoyuanS** [comment]
好的，非常感谢！
