### ISSUE TITLE
toy dataset

### ISSUE THREAD

**Issue by Weiyinyin11** [weiyinwei/MMGCN#43]
老哥你好，你有没有用你提供的toy dataset跑过这个实验呀？最终出来的结果大概是多少呢？

**Comment by weiyinwei** [comment]
这个我没测过，这个只是用来帮助大家了解一下模型的运行机制的。完全随机采样，有没有cold-start等问题我也不确定。

**Comment by Weiyinyin11** [comment]
> 

好的，谢谢老哥

**Comment by struggle123456789** [comment]
> 老哥你好，你有没有用你提供的toy dataset跑过这个实验呀？最终出来的结果大概是多少呢？



> 老哥你好，你有没有用你提供的toy dataset跑过这个实验呀？最终出来的结果大概是多少呢？

哥们，你用toy dataset 跑出来的结果是多少

**Comment by Jiangrijin** [comment]
> > 老哥你好，你有没有用你提供的toy dataset跑过这个实验呀？最终出来的结果大概是多少呢？
> 
> > 老哥你好，你有没有用你提供的toy dataset跑过这个实验呀？最终出来的结果大概是多少呢？
> 
> 哥们，你用toy dataset 跑出来的结果是多少

请问toy dataset在哪儿啊？

**Comment by Jiangrijin** [comment]
> 老哥你好，你有没有用你提供的toy dataset跑过这个实验呀？最终出来的结果大概是多少呢？

请问提供的toy dataset在哪儿啊？
