### ISSUE TITLE
movielens关键帧提取

### ISSUE THREAD

**Issue by srtianxia** [weiyinwei/MMGCN#5]
paper中说提取了movielens数据集的关键帧，用的什么工具包或算法呢？感谢

**Comment by weiyinwei** [comment]
感谢关注。
我用的是FFmpeg，一个通用的工具，可以用来分离视频音频，以及提取关键帧。
也可以使用opencv等工具。

**Comment by srtianxia** [comment]
能开源下数据就更好了 😁

**Comment by weiyinwei** [comment]
因为版权的问题，我们暂时只能先这样，现在在积极争取，希望尽快能完全吧数据开源。

**Comment by srtianxia** [comment]
对了 你们的YouTube链接是怎么获得的？

**Comment by weiyinwei** [comment]
你可以从movielens上找到你有兴趣的视频，然后在YouTube等视频分享网站找到它的宣传片。

**Comment by weiyinwei** [comment]
剩下的不用我说了吧

**Comment by srtianxia** [comment]
感谢您的解答

**Comment by srtianxia** [comment]
关键帧的选取是随机选取吗 ?   就是每一个视频会提取出很多个关键帧，每个item的关键帧是随机选取吗? 会不会有什么噪音之类的
