### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by Alan-JW** [weiyinwei/MMGCN#52]
@weiyinwei 您好，感谢您对开源社区的贡献，我想请问一下您是使用了什么方法对Movielens数据集提取出其音频视频文本特征？以及我怎么根据原始的快手和抖音数据进行预处理转换成您目前开源代码中能处理的形式？谢谢您的解答！

**Comment by weiyinwei** [comment]
您好，感谢关注。音频特征提取方法我在文章中进行了介绍，请参考“we separate audio tracks with FFmpeg6 and adopt VGGish to learn the acoustic deep learning features. ” 对于kwai和tiktok数据，没有过多操作，只是划分成了训练，测试，验证集。
