### ISSUE TITLE
关键帧抽取

### ISSUE THREAD

**Issue by srtianxia** [weiyinwei/MMGCN#6]
是使用 iframe (I帧抽取) 吗，一个视频会抽取出比较多的帧，对于一个item是随机选择一个帧的图片吗？感谢

**Comment by weiyinwei** [comment]
您好，我们在进行实验时提取k个关键帧，提取特征后进行mean pooling处理。

**Comment by srtianxia** [comment]
每一个视频提取的关键帧个数是不同的，有些比较多，可能有上百个，也是对所有的帧特征取均值吗？

**Comment by weiyinwei** [comment]
是的，我直接对所有帧的特征求平均. 单独模态特征的提取并不是我研究的重点，所以我并没有花费过多时间在这里。baseline使用相同的特征，可以说是一个公平的比较。我认为不必纠结于这一点。

**Comment by srtianxia** [comment]
好的 谢谢您
