### ISSUE TITLE
What's the initial feature of the users?

### ISSUE THREAD

**Issue by bbjy** [weiyinwei/MMGCN#7]
Hi @weiyinwei , thank you for your work. Although you cannot release the data in your work, would you please tell me what's the initial feature (or attributes, e.g. age, gender et al.) of the users you used for embedding? Or you only use the user id without other information about users? Thank you.

**Comment by weiyinwei** [comment]
Thanks for your attention. 
As your mentioned, we only used the user id without any other profile in the proposed approach. 
In addition, you could visit the link we released in our article and download the feature files from their owners.
