### ISSUE TITLE
Save embeddings after training

### ISSUE THREAD

**Issue by naveenkumarmarri** [weiyinwei/MMGCN#8]
In `train.py` for Tittok video, there is a flag called, `PATH_weight_save`, but I don't see that flag being used anywhere in the code to save the embeddings.
Is that feature yet to be made available?

**Comment by weiyinwei** [comment]
Thanks for your attention. 
Indeed, PATH_weight_save and Path_weight_load had been used to save and load the trained embedding matrix, but they are discarded now. 
I am sorry for confusing you.

**Comment by naveenkumarmarri** [comment]
@weiyinwei so, is there a way to save embeddings after the training is completed?

**Comment by weiyinwei** [comment]
Of course, you could check the document of Pytorch, some functions probably help you, like torch.save() and torch.load().
